service: 
  name: serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  
plugins:
 - serverless-plugin-optimize
 - serverless-dotenv-plugin
 - serverless-offline
 - serverless-plugin-warmup

custom:
  warmup:
    enable: true

package:
  individually: true
  exclude:
    - .git/**
    - src/**
    - test/**
    - doc/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true

functions:
  user:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any