service: 
  name: serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - doc/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true

functions:
  user:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
          private: true